on:
  push:
    branches: [main, master]
  release:
    types: [published]

name: pkgdown

jobs:
  pkgdown:
  runs-on: ubuntu-latest

  steps:
  - name: Install curl on Linux
    if: runner.os == 'Linux'
    run: sudo apt-get install curl

  - name: Send dispatch
    if: runner.os == 'Linux'
    run: curl -XPOST -u "${{ secrets.GITHUB_USERNAME}}:${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/ddsjoberg/website-test/actions/workflows/pkgdown.yaml/dispatches --data '{"ref": "main"}'
